### ISSUE TITLE
date_time_picker is not compatible with latest intl 0.18.1 package

### ISSUE THREAD

**Issue by kamleshwebtech** [m3uzz/date_time_picker#90]
Hi, I am using latest version of `date_time_picker` and `intl` in my flutter project. `Flutter version` is `3.14` but still not able to use date_time_picker package because it is using old intl package as dependency. That's why when I am compile my application, it gives me below error and it is not compiled:

`date_time_picker >=2.0.0 depends on intl ^0.17.0 and johndoedotin depends on intl 0.18.1, date_time_picker >=2.0.0 is forbidden.
So, because johndoedotin depends on date_time_picker ^2.1.0, version solving failed.`

`date_time_picker` dev team please check this issue and suggest me, how can we solve this and use your good `date_time_picker` package in my project. Thanks a lot.

Look forward to hear you.

**Comment by kamleshwebtech** [comment]
I have found a temporary solution of this issue for now

Add this dependency in your `pubspec.yaml` file:

`date_time_picker:
    git:
      url: https://github.com/DavidHDJ/date_time_picker.git
      ref: 2.1.1`

But `date_time_picker` dev team please take care this issue and fix it ASAP. Thanks a lot.

**Comment by FraPrime** [comment]
Hi, does this url still work ? I have tried my self but with no luck.
Did you put the entire url in the pubspec.yaml ?
Thanks

**Comment by arsarsars1** [comment]
Hi you can try the following. That is working. Thank you

  ```
date_time_picker:
    git:
      url: https://github.com/arsarsars1/date_time_picker.git
      ref: new_version 
```

**Comment by change-my-username-droid** [comment]
> Hi, does this url still work ? I have tried my self but with no luck. Did you put the entire url in the pubspec.yaml ? Thanks

```
try this

date_time_picker:
  git: 
      url: https://github.com/DavidHDJ/date_time_picker.git
      ref: 2.1.1
```
